<?php

declare(strict_types=1);

return [

    /*
    |----------------------------------------------------------------------
    | Protected extensions and automatic activation
    |----------------------------------------------------------------------
    | List of extensions that are forbidden to turn off or delete.
    */
    'protected' => [
        'Modules' => 'ExtensionsDebugger',

    ],

    /*
    |----------------------------------------------------------------------
    | Load order
    |----------------------------------------------------------------------
    | Hard order loading active extensions.
    | The extensions that are not here will be downloaded in an arbitrary order after the list.
    */
    'load_order' => [
        'Modules' => 'ExtensionsDebugger',
    ],

    /*
    |----------------------------------------------------------------------
    | Switchable Types
    |----------------------------------------------------------------------
    | List extension types where only one extension of a given type can be
    | active at a time. Enabling an extension of one of these types will
    | automatically disable the others of the same type.
    */
    'switch_types' => [
        'Themes',
    ],

    /*
    |--------------------------------------------------------------------------
    | Extensions Paths
    |--------------------------------------------------------------------------
    | Specify one or more directories where your extensions are located.
    | For example: [base_path('Extensions'), resource_path('extensions')]
    */
    'paths' => [
        'Modules' => base_path('extensions/Modules'),
        'Themes' => base_path('extensions/Themes'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Registry Cache
    |--------------------------------------------------------------------------
    | Discovery results are persisted to avoid rescanning extension directories
    | on every HTTP request. Cache is invalidated automatically when manifests
    | or composer files change, and after explicit discovery/mutations.
    */
    'registry' => [
        'cache' => [
            'enabled' => true,
            'path' => storage_path('framework/cache/extensions_registry.json'),
        ],

        'scan' => [
            'recursive_fallback' => true,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Extension Stubs
    |--------------------------------------------------------------------------
    | Configure the location of stub files and which groups are generated by
    | default when scaffolding a new extension.
    */
    'stubs' => [
        // Package stubs are used by default; override to use custom templates
        'path' => null,
        'default' => [
            'config',
            'console',
            'database',
            'events',
            'exceptions',
            'facades',
            'helpers',
            'http',
            'jobs',
            'lang',
            'listeners',
            'models',
            'notifications',
            'policies',
            'resources',
            'routes',
            'rules',
            'services',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Activator Class
    |--------------------------------------------------------------------------
    | The class responsible for managing the activation and deactivation of extensions.
    | \Gigabait93\Extensions\Activators\DbActivator::class
    */
    'activator' => \Gigabait93\Extensions\Activators\FileActivator::class,

    /*
    |--------------------------------------------------------------------------
    | JSON File for File Storage
    |--------------------------------------------------------------------------
    */
    'json_file' => base_path('storage/extensions.json'),

    /*
    |--------------------------------------------------------------------------
    | Composer Integration
    |--------------------------------------------------------------------------
    | Configure how dependency installation for extensions is executed.
    | `command` may be "composer" or a full command like "php composer.phar".
    */
    'composer' => [
        'command' => 'composer',
        'timeout' => 300,
        'lock_wait_seconds' => 15,
        'lock_seconds' => 330,
        'prefer_dist' => true,
        'no_dev' => false,
        'root_json' => base_path('composer.json'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Queue Overlap Protection
    |--------------------------------------------------------------------------
    | Prevent concurrent operations for the same extension in queued jobs.
    */
    'queue' => [
        'overlap_lock_seconds' => 300,
        'overlap_release_seconds' => 5,
    ],

    /*
    |--------------------------------------------------------------------------
    | Operations Store
    |--------------------------------------------------------------------------
    | Async operation statuses are persisted in DB by default. If migrations are
    | not applied yet, the tracker falls back to cache automatically.
    */
    'operations' => [
        'store' => 'database',
        'retention_hours' => 168,
        'prune_interval_seconds' => 300,
        'cache_ttl_hours' => 2,
    ],
];
