<?php

declare(strict_types=1);

return [

    /*
    |----------------------------------------------------------------------
    | Protected extensions and automatic activation
    |----------------------------------------------------------------------
    | List of extensions that are forbidden to turn off or delete.
    */
    'protected' => [
        'Modules' => 'ExtensionsDebugger',

    ],

    /*
    |----------------------------------------------------------------------
    | Load order
    |----------------------------------------------------------------------
    | Hard order loading active extensions.
    | The extensions that are not here will be downloaded in an arbitrary order after the list.
    */
    'load_order' => [
        'Modules' => 'ExtensionsDebugger',
    ],

    /*
    |----------------------------------------------------------------------
    | Switchable Types
    |----------------------------------------------------------------------
    | List extension types where only one extension of a given type can be
    | active at a time. Enabling an extension of one of these types will
    | automatically disable the others of the same type.
    */
    'switch_types' => [
        'Themes',
    ],

    /*
    |--------------------------------------------------------------------------
    | Extensions Paths
    |--------------------------------------------------------------------------
    | Specify one or more directories where your extensions are located.
    | For example: [base_path('Extensions'), resource_path('extensions')]
    */
    'paths' => [
        'Modules' => base_path('extensions/Modules'),
        'Themes' => base_path('extensions/Themes'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Extension Stubs
    |--------------------------------------------------------------------------
    | Configure the location of stub files and which groups are generated by
    | default when scaffolding a new extension.
    */
    'stubs' => [
        // Package stubs are used by default; override to use custom templates
        'path' => null,
        'default' => [
            'config',
            'console',
            'database',
            'events',
            'exceptions',
            'facades',
            'helpers',
            'http',
            'jobs',
            'lang',
            'listeners',
            'models',
            'notifications',
            'policies',
            'resources',
            'routes',
            'rules',
            'services',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Activator Class
    |--------------------------------------------------------------------------
    | The class responsible for managing the activation and deactivation of extensions.
    | \Gigabait93\Extensions\Activators\DbActivator::class
    */
    'activator' => \Gigabait93\Extensions\Activators\FileActivator::class,

    /*
    |--------------------------------------------------------------------------
    | JSON File for File Storage
    |--------------------------------------------------------------------------
    */
    'json_file' => base_path('storage/extensions.json'),
];
