name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        php: ['8.3']
        laravel: ['12.x']
        include:
          - laravel: 12.x
            testbench: 10.x
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          tools: composer:v2
          extensions: mbstring, json, dom, curl, sqlite3

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php${{ matrix.php }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Run PHPStan static analysis
        run: vendor/bin/phpstan analyse --no-progress --error-format=github

      - name: Run PHP-CS-Fixer (dry-run)
        run: vendor/bin/php-cs-fixer fix --dry-run --using-cache=no --diff

      - name: Upload coverage to Codecov
        if: matrix.php == '8.3' && matrix.laravel == '12.x'
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

